// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoutingService.Infrastructure.Persistence;

#nullable disable

namespace RoutingService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925155536_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TwoGisRouteServer.Domain.Entities.RouteLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageTaxiPrice")
                        .HasColumnType("float");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<double>("DurationInTrafficMinutes")
                        .HasColumnType("float");

                    b.Property<double>("DurationWithoutTrafficMinutes")
                        .HasColumnType("float");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("TrafficLevel")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("RouteLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
