// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoutingService.Infrastructure.Persistence;

#nullable disable

namespace RoutingService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925161249_Adding_Automatisation")]
    partial class Adding_Automatisation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoutingService.Domain.Entities.RouteSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageTaxiPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<double>("DurationInTrafficMinutes")
                        .HasColumnType("float");

                    b.Property<double>("DurationWithoutTrafficMinutes")
                        .HasColumnType("float");

                    b.Property<int>("TrackedRouteId")
                        .HasColumnType("int");

                    b.Property<double>("TrafficLevel")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TrackedRouteId", "CapturedAt");

                    b.ToTable("RouteSnapshots");
                });

            modelBuilder.Entity("RoutingService.Domain.Entities.TrackedRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("TrackedRoutes");
                });

            modelBuilder.Entity("TwoGisRouteServer.Domain.Entities.RouteLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageTaxiPrice")
                        .HasColumnType("float");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<double>("DurationInTrafficMinutes")
                        .HasColumnType("float");

                    b.Property<double>("DurationWithoutTrafficMinutes")
                        .HasColumnType("float");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("TrafficLevel")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("RouteLogs");
                });

            modelBuilder.Entity("RoutingService.Domain.Entities.RouteSnapshot", b =>
                {
                    b.HasOne("RoutingService.Domain.Entities.TrackedRoute", "TrackedRoute")
                        .WithMany("Snapshots")
                        .HasForeignKey("TrackedRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedRoute");
                });

            modelBuilder.Entity("RoutingService.Domain.Entities.TrackedRoute", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
